/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.junit.Test;

public class MainTest 
{
    @Test 
    public void mainHasAGreeting() 
    {
    }
}
